### ISSUE TITLE
0.1.0 roadmap

### ISSUE THREAD

**Issue by icarus-sullivan** [icarus-sullivan/serverless-plugin-staging#1]
- add regular expression support
_example_
```
staging:
  excludeFunctions:
    beta:
      - /sync.*Processor/
```
- add an only option to reduce duplication 
_example_
```
staging:
  only:
    prod:
      - UploadBucket
    beta:
      - UploadBucket
```
